export interface ToolExplanation {
  title: string;
  subtitle: string;
  whatIsText: string;
  howToUseSteps: string[];
  keyFeatures: string[];
  commonUseCases: string[];
  faq: { question: string; answer: string }[];
}

export const TOOL_EXPLANATIONS: Record<string, ToolExplanation> = {
  "json-formatter": {
    title: "Comprehensive Guide to JSON Formatting & Validation",
    subtitle: "Everything you need to know about parsing, beautifying, and validating JSON data.",
    whatIsText: `JSON (JavaScript Object Notation) is a lightweight, text-based, human-readable data interchange format widely used in modern web applications, REST APIs, microservices, and configuration files. Standard JSON structures data using key-value pairs and ordered arrays. However, raw JSON generated by backend servers or API endpoints is often minified into a single line to save bandwidth. This makes manual inspection, debugging, and editing extremely difficult for developers.

Our JSON Formatter & Beautifier processes your JSON string locally in real-time. It validates syntax errors such as trailing commas, missing quotes, or unclosed brackets, and formats the structure with customizable indentation levels (2 spaces, 4 spaces, or tabs). Because execution happens 100% on the client side inside your web browser, sensitive API responses, customer payloads, and credentials never cross the network.`,
    howToUseSteps: [
      "Paste or type your raw, minified, or unformatted JSON text into the input panel on the left.",
      "Click the 'Format / Beautify' button to instantaneously parse, validate, and format your JSON payload.",
      "Use the controls to adjust indentation spacing, minify the output, or expand/collapse tree nodes.",
      "Copy the formatted JSON to your clipboard with one click or download it directly as a .json file."
    ],
    keyFeatures: [
      "Instant syntax validation with precise error line and column highlighting.",
      "Support for customizable indentation options (2 spaces, 4 spaces, tab indentation).",
      "One-click minification for optimized network bandwidth and production storage.",
      "Zero-server latency: 100% local client-side execution for complete data privacy."
    ],
    commonUseCases: [
      "Inspecting and debugging complex REST API and GraphQL response payloads.",
      "Formatting package.json, tsconfig.json, or application configuration files.",
      "Cleaning up unstructured log outputs from CloudWatch, Datadog, or server logs."
    ],
    faq: [
      {
        question: "Is my JSON data safe when formatted in mytoolsbox?",
        answer: "Yes, 100%. All formatting and parsing operations run strictly within your web browser JavaScript runtime. No text or payload is ever transmitted over the internet."
      },
      {
        question: "How does the formatter handle invalid JSON syntax?",
        answer: "If your input contains syntax errors—such as missing quotes around keys or trailing commas—the tool pinpoints the exact line number and error message so you can fix it immediately."
      }
    ]
  },
  "json-compare": {
    title: "Understanding JSON Diff & Structure Comparison",
    subtitle: "Compare two JSON objects side-by-side to pinpoint added, modified, or deleted fields.",
    whatIsText: `Comparing JSON objects manually line-by-line is error-prone, especially when working with nested structures, microservice API contracts, or database schemas. A JSON comparator parses both left (original) and right (modified) JSON inputs, normalizes key order, and highlights structural differences using visual color-coded diff indicators.

This tool evaluates object depth, array elements, primitives, and null values. It highlights additions in green, deletions in red, and value modifications in yellow, allowing engineering teams to audit API response changes, configuration drift, and database schema updates in seconds.`,
    howToUseSteps: [
      "Paste your original JSON object into the Left Input panel.",
      "Paste the updated or modified JSON object into the Right Input panel.",
      "Click 'Compare JSON' to compute side-by-side and inline structural differences.",
      "Review highlighted additions, deletions, and modified values in the visual diff viewer."
    ],
    keyFeatures: [
      "Side-by-side split view and inline unified diff visualization.",
      "Recursive deep object comparison including nested arrays and primitives.",
      "Automatic key sorting for reliable diff computation regardless of property order.",
      "Summary statistics reporting exact counts of added, modified, and removed keys."
    ],
    commonUseCases: [
      "Comparing API v1 vs v2 payloads during backend migrations.",
      "Auditing configuration changes across staging and production environments.",
      "Validating database record snapshots before and after migration scripts."
    ],
    faq: [
      {
        question: "Does property order affect the JSON comparison?",
        answer: "No. The comparator automatically normalizes key ordering so that object properties are compared by key path rather than arbitrary string positions."
      },
      {
        question: "Can I compare large JSON files?",
        answer: "Yes. The diff engine is optimized for high performance and can handle multi-megabyte JSON payloads directly in your browser."
      }
    ]
  },
  "text-diff": {
    title: "Mastering Text Diff & Code Comparison",
    subtitle: "Identify additions, deletions, and line changes across source code and documents.",
    whatIsText: `Text diffing is a fundamental developer capability for tracking revision histories, code patches, and document variations. By executing line-by-line and character-level comparisons, a text diff tool computes the shortest edit script (Myers diff algorithm) required to transform one string into another.

Whether you are auditing code snippets, comparing server configuration scripts, or reviewing Markdown documentation before committing to source control, our Text Diff tool provides immediate visual feedback with clear line numbers, split diff views, and unified diff output.`,
    howToUseSteps: [
      "Paste original text or code into the left text area.",
      "Paste revised text or code into the right text area.",
      "Observe highlighted line additions (green), deletions (red), and inline text edits.",
      "Toggle between Split View (side-by-side) and Unified View (single stream)."
    ],
    keyFeatures: [
      "Dual view modes: Side-by-Side Split View and Single Column Unified View.",
      "Character-level diff highlighting for precise word changes within modified lines.",
      "Ignore whitespace and case sensitivity toggle controls.",
      "Instant copyable unified patch format for git compatibility."
    ],
    commonUseCases: [
      "Reviewing pull request code snippets before merging.",
      "Comparing environment variable files (.env.example vs .env.production).",
      "Auditing policy documents, SQL queries, or legal texts."
    ],
    faq: [
      {
        question: "How are line breaks and indentation handled?",
        answer: "You can toggle whether leading whitespace and blank lines are included in diff calculations."
      },
      {
        question: "Can I copy the diff output for Git patches?",
        answer: "Yes, you can copy the standard unified diff output directly into your terminal or patch tools."
      }
    ]
  },
  "base64": {
    title: "Everything About Base64 Encoding & Decoding",
    subtitle: "Convert binary data, text strings, and images to standard RFC 4648 Base64 strings.",
    whatIsText: `Base64 is a binary-to-text encoding scheme that represents binary data in an ASCII string format by translating it into a radix-64 representation. Designed under RFC 4648, Base64 ensures that binary payloads—such as images, PDF files, or cryptographic signatures—can be safely transmitted across networks without byte corruption in protocol layers designed strictly for text (such as Email SMTP, HTML inline data URIs, or JSON payloads).

Our Base64 Encoder & Decoder supports both standard Base64 encoding and URL-safe Base64 variants (substituting + and / with - and _). It also features live image file preview encoding, enabling you to convert PNG, JPEG, SVG, or WebP files directly into inline data URIs for CSS and HTML.`,
    howToUseSteps: [
      "Select 'Encode' or 'Decode' tab depending on your objective.",
      "Input plain text, URL parameters, or upload an image file.",
      "View instant Base64 encoded output or decoded UTF-8 string.",
      "Copy the result or use the HTML Data URI snippet for frontend web development."
    ],
    keyFeatures: [
      "Standard Base64 (RFC 4648) and URL-safe Base64 encoding support.",
      "Real-time bidirectional conversion as you type.",
      "Image file upload to Base64 data URI converter with instant visual preview.",
      "Full UTF-8 multibyte character support for international scripts and emojis."
    ],
    commonUseCases: [
      "Embedding small images directly into CSS stylesheets or HTML <img> tags.",
      "Encoding Basic Authentication credentials (username:password) for HTTP headers.",
      "Decoding JWT payload segments or obfuscated web parameters."
    ],
    faq: [
      {
        question: "Does Base64 provide encryption or security?",
        answer: "No. Base64 is an encoding format, NOT encryption. Anyone can decode a Base64 string back to original data. Never store raw passwords using Base64 alone."
      },
      {
        question: "What is URL-safe Base64?",
        answer: "URL-safe Base64 replaces the '+' and '/' characters with '-' and '_' so the string can be placed inside web URL parameters without requiring URL escaping."
      }
    ]
  },
  "jwt-decoder": {
    title: "Guide to JSON Web Token (JWT) Decoding & Inspection",
    subtitle: "Decode, inspect, and verify JWT headers, claims payloads, and signatures.",
    whatIsText: `JSON Web Tokens (JWT) specified in RFC 7519 are an open, industry-standard method for representing claims securely between two parties. A JWT consists of three Base64URL-encoded segments separated by dots (.): Header, Payload, and Signature.

JWTs are extensively used in OAuth 2.0, OpenID Connect, and modern single-page web applications for stateless user authentication and access control. Decoding a JWT allows developers to inspect key claim properties such as issue date (iat), expiration timestamp (exp), issuer (iss), subject (sub), and custom authorization roles without needing secret keys to view the claims payload.`,
    howToUseSteps: [
      "Paste your encoded JWT string (e.g. eyJhbGciOi...) into the token input box.",
      "The decoder immediately splits and parses the Header, Payload, and Signature parts.",
      "Check expiration status (exp) with human-readable date and countdown timers.",
      "Inspect user roles, scopes, and custom claim attributes formatted in color-coded JSON."
    ],
    keyFeatures: [
      "Instant breakdown of Header (algorithm & token type), Payload (claims), and Signature.",
      "Automatic expiration time checking with relative time remaining indicators.",
      "Color-coded JSON syntax rendering for claims and token header fields.",
      "100% private: Tokens are decoded strictly inside your browser window."
    ],
    commonUseCases: [
      "Debugging OAuth 2.0 and Auth0 access token scopes during API development.",
      "Verifying user permissions, tenant IDs, and session expiration timestamps.",
      "Inspecting Firebase Auth, Supabase, or AWS Cognito authentication tokens."
    ],
    faq: [
      {
        question: "Is it safe to paste production JWTs into this tool?",
        answer: "Yes. All decoding runs entirely locally in client JavaScript memory. No token is ever sent over network connections."
      },
      {
        question: "Can this tool verify the signature of my token?",
        answer: "The tool inspects signature algorithm headers. Signature cryptographic verification requires providing your server secret or public key, which remains strictly in your local session."
      }
    ]
  },
  "regex-tester": {
    title: "Regular Expressions (Regex) Testing & Pattern Matching",
    subtitle: "Build, test, and debug JavaScript regular expressions with real-time match highlighting.",
    whatIsText: `Regular expressions (regex or regexp) are powerful sequences of characters that define search patterns. Used across nearly every programming language—including JavaScript, Python, Java, Go, and SQL—regex enables pattern validation (email addresses, phone numbers, IP addresses), string parsing, search-and-replace routines, and lexical analysis.

Writing complex regular expressions can be challenging without feedback. Our Regex Tester provides real-time pattern evaluation against test strings, displaying match counts, capture groups, match index positions, and full flag configuration options (global g, case-insensitive i, multiline m, dotall s, unicode u).`,
    howToUseSteps: [
      "Enter your regular expression pattern in the Regex Pattern input.",
      "Select your desired regex flags (g, i, m, s, u, y).",
      "Type or paste sample text in the Test String area.",
      "View highlighted match results, capture groups, and match indexes in real-time."
    ],
    keyFeatures: [
      "Live match highlighting as you edit your regular expression or test string.",
      "Detailed capture group inspector showing indexed and named capture groups.",
      "Preset library of common patterns (Email, URL, IPv4, Phone Number, Date).",
      "Instant error reporting for invalid regex syntax."
    ],
    commonUseCases: [
      "Validating user input forms (email formats, password strength rules).",
      "Parsing log files to extract IP addresses, status codes, and timestamps.",
      "Building search and replace rules for text processing pipelines."
    ],
    faq: [
      {
        question: "Which Regex engine is used by this tool?",
        answer: "The tool utilizes the native ECMAScript / JavaScript regular expression engine built into modern web browsers, supporting modern features like lookbehinds and named capture groups."
      },
      {
        question: "What does the 'g' flag do?",
        answer: "The global 'g' flag ensures the expression matches all occurrences in the test text rather than stopping after the first match."
      }
    ]
  },
  "url-encoder": {
    title: "URL Encoding & Decoding (Percent-Encoding) Guide",
    subtitle: "Safely encode and decode query parameters, path components, and URI strings.",
    whatIsText: `URL encoding (also known as percent-encoding) converts reserved characters in Uniform Resource Identifiers (URIs) into standard ASCII format defined by RFC 3986. Reserved characters such as spaces, ampersands (&), question marks (?), equals signs (=), and slashes (/) have special syntax meanings in URLs.

If unescaped user input or binary strings are included in URL query parameters, browsers and web servers may misinterpret query boundaries or drop characters. URL encoding replaces non-ASCII or reserved characters with a percent sign (%) followed by two hexadecimal digits representing the byte value.`,
    howToUseSteps: [
      "Select 'Encode' or 'Decode' mode.",
      "Enter your URL, query string, or parameter string into the text field.",
      "View the transformed percent-encoded string (encodeURIComponent) instantly.",
      "Use 'Encode Full URL' vs 'Encode Component' options based on your API routing needs."
    ],
    keyFeatures: [
      "Bidirectional conversion between raw strings and percent-encoded URIs.",
      "Support for encodeURIComponent (parameters) and encodeURI (full links).",
      "Handling of special symbols, international UTF-8 characters, and spaces (+ or %20).",
      "One-click copy and quick clear actions."
    ],
    commonUseCases: [
      "Formatting complex query parameters for REST API GET requests.",
      "Escaping redirect URIs in OAuth authentication parameters.",
      "Decoding messy tracking URLs and web analytics strings."
    ],
    faq: [
      {
        question: "What is the difference between encodeURI and encodeURIComponent?",
        answer: "encodeURI preserves URL structure characters like ':', '/', '?', and '#', whereas encodeURIComponent encodes all reserved characters, making it ideal for query string parameter values."
      },
      {
        question: "Why are spaces sometimes encoded as '+' instead of '%20'?",
        answer: "In application/x-www-form-urlencoded form submissions, spaces are traditionally encoded as '+', whereas standard URI percent-encoding uses '%20'. Our tool supports both formats."
      }
    ]
  },
  "hash-generator": {
    title: "Cryptographic Hash Generator (MD5, SHA-1, SHA-256, SHA-512)",
    subtitle: "Generate secure cryptographic message digests and file checksums instantly.",
    whatIsText: `A cryptographic hash function is a mathematical algorithm that transforms an arbitrary block of data into a fixed-size string of characters (the hash digest). A key property of cryptographic hashes is that they are deterministic and one-way: the same input will always produce the exact same hash, but it is computationally infeasible to reconstruct the original input from the hash value alone.

Common hash functions include SHA-256 and SHA-512 (Secure Hash Algorithms used widely in Bitcoin, SSL/TLS certificates, and git commits), alongside legacy algorithms like MD5 and SHA-1 used for fast checksum verification. Our Hash Generator computes multi-algorithm digests simultaneously using standard Web Crypto APIs.`,
    howToUseSteps: [
      "Type or paste your text input into the text field.",
      "The tool calculates MD5, SHA-1, SHA-256, and SHA-512 digests in real-time.",
      "Toggle output formats between Hexadecimal string and Base64 encoded string.",
      "Copy individual hash digests to your clipboard."
    ],
    keyFeatures: [
      "Simultaneous computation of MD5, SHA-1, SHA-256, and SHA-512 digests.",
      "High performance using browser Web Crypto API algorithms.",
      "Hexadecimal and Base64 output representation toggles.",
      "100% private: Data never leaves your local machine."
    ],
    commonUseCases: [
      "Verifying file download integrity using published checksums.",
      "Generating unique record hashes for cache key management.",
      "Comparing data payloads without transmitting sensitive raw text."
    ],
    faq: [
      {
        question: "Should MD5 or SHA-1 be used for password hashing?",
        answer: "No. MD5 and SHA-1 are cryptographically broken and vulnerable to collision attacks. For passwords, use modern salted key derivation functions like bcrypt or Argon2."
      },
      {
        question: "Is SHA-256 secure?",
        answer: "Yes, SHA-256 is part of the SHA-2 family and remains an industry standard for data integrity, digital signatures, and security protocols."
      }
    ]
  },
  "uuid-generator": {
    title: "UUID v4 & Cryptographic Password Generator",
    subtitle: "Generate RFC 4122 compliant UUIDs and cryptographically secure passwords.",
    whatIsText: `Universally Unique Identifiers (UUIDs) are 128-bit numbers standardized under RFC 4122. A UUID Version 4 is generated using cryptographically strong pseudo-random numbers, producing identifiers with 122 bits of entropy. The probability of a collision (two identical UUID v4 values) is practically zero, making them ideal for primary keys in distributed databases, microservice request IDs, and session tokens.

Alongside UUID generation, our utility includes a Cryptographic Password Generator powered by window.crypto.getRandomValues(). You can customize character length, uppercase letters, lowercase letters, numbers, and special symbols to generate secure, unguessable credentials.`,
    howToUseSteps: [
      "Select bulk generation quantity (1 to 100 UUIDs at once).",
      "Toggle UUID format options (lowercase, uppercase, hyphens, or hyphenless).",
      "Switch to Password Generator tab to set length and character sets.",
      "Click 'Generate' and copy individual identifiers or export full lists."
    ],
    keyFeatures: [
      "RFC 4122 compliant UUID v4 generation backed by crypto.getRandomValues().",
      "Bulk generation capability producing up to 100 unique UUIDs instantly.",
      "Customizable password generator with strength indicators and character filters.",
      "One-click copy to clipboard for single or batch identifiers."
    ],
    commonUseCases: [
      "Creating primary key IDs for database tables (PostgreSQL, MongoDB, DynamoDB).",
      "Generating correlation IDs for distributed microservice logging.",
      "Creating high-entropy passwords and API secret keys."
    ],
    faq: [
      {
        question: "How random are the generated UUIDs?",
        answer: "Our tool relies on the browser's Web Crypto API (crypto.getRandomValues), providing cryptographically secure hardware-seeded randomness."
      },
      {
        question: "What are the odds of two UUID v4 values colliding?",
        answer: "After generating 1 billion UUIDs per second for 85 years, the probability of a single collision is approximately 50%. You can safely use UUIDs across distributed systems."
      }
    ]
  },
  "color-converter": {
    title: "Color Studio: HEX, RGB, HSL, and OKLCH Converter",
    subtitle: "Convert, preview, and audit web colors with contrast ratio checks.",
    whatIsText: `Color representation in web design and CSS encompasses multiple color spaces: HEX (hexadecimal), RGB (Red, Green, Blue), HSL (Hue, Saturation, Lightness), and modern color models like OKLCH. Each format has distinct advantages: HEX is compact, HSL is intuitive for adjustments, and OKLCH provides perceptually uniform color adjustments across displays.

Our Color Studio tool enables live color conversion across all major CSS color formats. It includes a built-in contrast ratio checker adhering to WCAG 2.1 accessibility guidelines, helping front-end developers ensure legible text contrast on light and dark UI surfaces.`,
    howToUseSteps: [
      "Pick a color using the visual color picker or paste a HEX, RGB, or HSL code.",
      "View instant conversions across HEX, RGB, HSL, and CSS color functions.",
      "Inspect WCAG 2.1 accessibility contrast ratios against white and black backgrounds.",
      "Copy CSS color declarations with a single click."
    ],
    keyFeatures: [
      "Bidirectional conversion between HEX, RGB, HSL, and CSS variables.",
      "Interactive visual color picker and color palette generator.",
      "WCAG 2.1 contrast ratio audit (AA and AAA compliance badges).",
      "Copyable CSS code snippets for Tailwind CSS and standard stylesheets."
    ],
    commonUseCases: [
      "Translating designer Figma color codes into production CSS variables.",
      "Auditing color accessibility and legibility for UI design systems.",
      "Creating dark mode color palettes with consistent saturation."
    ],
    faq: [
      {
        question: "What is WCAG AA contrast compliance?",
        answer: "WCAG 2.1 AA requires a minimum contrast ratio of 4.5:1 for normal body text and 3:1 for large text against its background."
      },
      {
        question: "Does this tool support alpha channel transparency?",
        answer: "Yes, 8-digit HEX (#RRGGBBAA), RGBA, and HSLA values with opacity percentages are fully supported."
      }
    ]
  },
  "cron-parser": {
    title: "Cron Expression Parser & Schedule Explainer",
    subtitle: "Decode cron schedules into plain English human language and upcoming execution dates.",
    whatIsText: `Cron is a time-based job scheduler in Unix-like operating systems widely used to schedule background tasks, backup scripts, database cleanups, and automated email dispatches. A standard cron expression consists of 5 fields (minute, hour, day of month, month, day of week) or 6 fields including seconds.

Cryptic cron strings like "*/15 2,14 * * 1-5" can be confusing to interpret manually. Our Cron Expression Parser converts syntax strings into plain English human descriptions and calculates the exact next 5 upcoming execution timestamps according to your local time zone.`,
    howToUseSteps: [
      "Type or paste your 5-part or 6-part cron expression into the input field.",
      "Read the instant human-readable English explanation of your schedule.",
      "Inspect the list of upcoming 5 trigger dates and times.",
      "Use preset shortcuts for common schedules (Every minute, Every midnight, Every Monday)."
    ],
    keyFeatures: [
      "Instant translation of 5-part standard cron expressions into natural language.",
      "Calculates the next 5 upcoming run times with local timezone support.",
      "Includes a quick-reference library of common server cron patterns.",
      "Syntax validation reporting invalid ranges, step values, or wildcards."
    ],
    commonUseCases: [
      "Configuring GitHub Actions workflows and Vercel Cron Jobs.",
      "Setting up server backup cron tasks in crontab.",
      "Validating scheduled background jobs in Node.js (node-cron) or Python (Celery)."
    ],
    faq: [
      {
        question: "What do the 5 cron fields represent?",
        answer: "In order: 1) Minute (0-59), 2) Hour (0-23), 3) Day of Month (1-31), 4) Month (1-12), 5) Day of Week (0-6, where 0 is Sunday)."
      },
      {
        question: "What does the wildcard asterisk (*) mean in cron?",
        answer: "An asterisk means 'every' or 'all valid values' for that field (e.g., * in the hour position means every hour)."
      }
    ]
  },
  "sql-formatter": {
    title: "SQL Formatter & Query Beautifier",
    subtitle: "Format, beautify, and clean up SQL queries for PostgreSQL, MySQL, SQLite, and SQL Server.",
    whatIsText: `SQL (Structured Query Language) is the standard database query language. Raw SQL statements created by ORMs, backend loggers, or quick ad-hoc queries are often formatted as long, unreadable single lines with inconsistent keyword capitalization.

A SQL Formatter restructures database queries by capitalizing SQL keywords (SELECT, FROM, WHERE, JOIN, GROUP BY), applying consistent clause indentations, and placing subqueries and JOIN operations on clean new lines. Beautiful SQL improves code review readability and speeds up database debugging.`,
    howToUseSteps: [
      "Paste your raw or unformatted SQL query into the input editor.",
      "Choose your SQL dialect preference (Standard SQL, PostgreSQL, MySQL, SQLite).",
      "Click 'Format SQL' to beautify keywords, indents, and clause line breaks.",
      "Copy the formatted query directly into your database management client."
    ],
    keyFeatures: [
      "Automatic keyword uppercase transformation (SELECT, FROM, LEFT JOIN, WHERE).",
      "Clause alignment and subquery block indentation.",
      "Dialect support for PostgreSQL, MySQL, SQLite, and T-SQL.",
      "One-click copy and query sample preset loader."
    ],
    commonUseCases: [
      "Beautifying raw SQL queries extracted from ORM logs (Prisma, Drizzle, Sequelize).",
      "Formatting complex analytical queries with multiple CTEs and JOIN statements.",
      "Preparing clean SQL code snippets for documentation and team code reviews."
    ],
    faq: [
      {
        question: "Does formatting SQL change query performance?",
        answer: "No. SQL formatters only adjust whitespace and keyword casing. Database query planners parse the abstract syntax tree identically regardless of whitespace."
      },
      {
        question: "Is my database query kept private?",
        answer: "Yes. All SQL formatting is performed locally inside your web browser. No table names, schemas, or data queries are sent to external servers."
      }
    ]
  },
  "timestamp-converter": {
    title: "Unix Timestamp & Date Time Converter",
    subtitle: "Convert Unix epoch timestamps to human-readable dates, ISO 8601 strings, and UTC time.",
    whatIsText: `A Unix timestamp (also known as Epoch time or POSIX time) measures time as the total number of seconds (or milliseconds) that have elapsed since January 1, 1970 00:00:00 UTC (the Unix Epoch), excluding leap seconds. Unix timestamps are universally used in computer systems, database indexes, API headers, and JWT tokens because they are integer numbers independent of geographic time zones.

Our Timestamp Converter translates between 10-digit second timestamps, 13-digit millisecond timestamps, UTC dates, ISO 8601 strings, and your local browser timezone. It also features a real-time live clock displaying current epoch time.`,
    howToUseSteps: [
      "Enter a 10-digit (seconds) or 13-digit (milliseconds) timestamp, or select a date/time.",
      "The tool automatically detects second vs millisecond formats.",
      "View converted dates in Local Time, UTC Time, ISO 8601, and RFC 2822 formats.",
      "Click 'Now' to grab the current epoch timestamp instantly."
    ],
    keyFeatures: [
      "Automatic detection of seconds (10-digit) and milliseconds (13-digit) epoch values.",
      "Simultaneous conversion across Local Time, UTC, ISO 8601, and Relative Time ('2 hours ago').",
      "Live updating current Unix timestamp counter.",
      "Date picker integration for bidirectional Date-to-Timestamp conversion."
    ],
    commonUseCases: [
      "Debugging database created_at / updated_at timestamps.",
      "Inspecting JWT expiration (exp) and issued-at (iat) time values.",
      "Converting server log timestamps into local readable date strings."
    ],
    faq: [
      {
        question: "What is the difference between a 10-digit and 13-digit timestamp?",
        answer: "A 10-digit timestamp counts seconds since 1970 (common in Linux and C), while a 13-digit timestamp counts milliseconds (standard in JavaScript Date.now() and Java)."
      },
      {
        question: "What is the Year 2038 problem (Y2K38)?",
        answer: "On January 19, 2038, 32-bit signed integers will overflow. Modern 64-bit systems and JavaScript numbers prevent this issue."
      }
    ]
  }
};
